### ISSUE TITLE
ability to pull GTK2 test results

### ISSUE THREAD

**Issue by LeoUfimtsev** [ericwill/build_test_script#10]
I'd like to know if GTK2 breakage occurs due to my patches.

Not that it matters much, but kinda good to know.

If you have time, it would be nice to have the ability to pull GTK2 changes.

Btw, I assume "-o GTK" means gtk3, which is not quite clear from documentation?

**Comment by ericwill** [comment]
"-o GTK" will pull in both GTK2 and GTK3. I can make an option for GTK2, GTK3, or both.
